### ISSUE TITLE
Fan Icon as Volume

### ISSUE THREAD

**Issue by koupus** [AntonioMeireles/homebridge-vieramatic#13]
Hello Antonio,
Hope you are fine at this time.

I just want to know if the fan icon for the volume set is still normal? (Capture below)
Or is there something i can do to have a good icon?

Take care of yourself and family!

Bye, Tom

![3F52714B-DB79-4C38-84E1-0CC87D3FB875](https://user-images.githubusercontent.com/50924184/77616645-6f9f9a00-6f32-11ea-95b6-ee57f363ceb4.png)
![E37BB441-9F04-48AA-94AF-102243148F71](https://user-images.githubusercontent.com/50924184/77616653-729a8a80-6f32-11ea-8e8c-284f02ce35c0.png)

**Comment by AntonioMeireles** [comment]
> Hello Antonio,
> Hope you are fine at this time.
> 

Trying 😷 . things going havoc everywhere, sadly. Hope you, and yours, coping with this in the less painful way possible!

Now, back to things somewhat easier to explain. 

strictly, the canonical way to change the volume in the home app on a TV is by using the phones hardware volume keys (which my plugin supports).

OTOH, and per the Apple's UI guidelines there is no way of - inside the home app - to know or change what's the TV volume level, which i find to be a  very handy thing (say you are in another room, and want to lower the TV's volume, etc).

So, in order to have that i added the "fan" as a way to represent TV's volume (on very early plugin versions it was a lamp - but then some people rightfully complained about breakage with siri automations relating to lights so i changed it to be a fan (which way less people have :-) ).

I understand that this fan thing is not for everybody's  taste, so soon it will become an optional feature configurable via 'config.json'

hope this answers your question, if not, just get back :-) (&& thanks for your patience) 

All the best, 

António

**Comment by AntonioMeireles** [comment]
closing per #22. please reopen if you have (new) issues

Thanks for your patience
