### ISSUE TITLE
Error on initialising

### ISSUE THREAD

**Issue by NeilBain** [AntonioMeireles/homebridge-vieramatic#18]
From logs...

`[4/24/2020, 3:53:18 PM] [PanasonicVieraTV] Error: An unexpected error happened while adding Viera TV (at '192.168.1.199') as an homebridge Accessory.

TypeError: Cannot read property 'hiden' of undefined
    at VieramaticPlatform.init (/usr/lib/node_modules/homebridge-vieramatic/lib/homebridge.coffee:479:17)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)`

Running on Ubuntu 18.04

**Comment by AntonioMeireles** [comment]
Hi, 

thanks for reporting! test please 0.9.9 version of plugin that i just released and please repot back if  it fixes your issue. if it does not could you mail me directly please (address is in this project git commit logs) so that we can debug this offline ? 

Thanks in advance and have a great weekend!

**Comment by AntonioMeireles** [comment]
@NeilBain 

0.9.12 is just out :-) with the fix. Thanks again for your time and patience!
