### ISSUE TITLE
Legacy Input Control

### ISSUE THREAD

**Issue by ValoV83** [AntonioMeireles/homebridge-vieramatic#46]
I was wondering if it’s possible to configure the plugin or add support to be able to switch to legacy analogue inputs like the AV1 and AV2 inputs if defined within the config.json?

**Comment by AntonioMeireles** [comment]
a priori it should be, ... albeit i have nothing here to plug into the TV to test ... 

will take a look soonish, as you just volunteered to beta test ;-)

**Comment by ValoV83** [comment]
> a priori it should be, ... albeit i have nothing here to plug into the TV to test ...
> 
> will take a look soonish, as you just volunteered to beta test ;-)

Excellent! Thanks very much for having a look to see if it's possible. Happy to test it out as well :)

**Comment by AntonioMeireles** [comment]
@ValoV83 

this is tricky. Long story shortened is...

currently from a feature set standpoint the biggest limitation of this plugin is that it has no way to know when it connects to the TV what the TV is actually doing (other than finding if it is ON or OFF and the volume/mute status). I.E. from the available stuff regarding the inner workings of the TV afaict there is no way to get TV's API to tell us if a given HDMI port is active, or if it is some app or some AV port. 

To add to this misery and unlike for HDMI ports where we have `NRC_HDMI${hdmiInput}-ONOFF` where `hdmiInput` in in range `[1-4]`, we do not have available anything with similar granularity. the best we have is `NRC_CHG_INPUT-ONOFF` which cycles all the available  inputs including the AV ones if set.  the problem is that this cycling is relative to whatever is running  so we have no way to know when triggering it what is actually being  next in the queued loop. 

So, unless i - or some kind soul - make some breakthrough regarding hidden API features, we have no way to implement this in sight 😞 

Thanks again for your patience!

**Comment by ValoV83** [comment]
@AntonioMeireles 

Thanks for investigating the possibility of adding support for legacy analogue inputs to the plugin. 

It would be nice for my setup but by no means a deal breaker, I just thought I'd see if it's possible which by the sounds of things it's currently not due to the API limitations.

Thanks again for investigating but I'm happy to close my ticket. If by some miracle it does become possible it would be a very welcome addition :)
