### ISSUE TITLE
Doesn’t show up in Homekit

### ISSUE THREAD

**Issue by lDavidl** [AntonioMeireles/homebridge-vieramatic#91]
The accessory doesn’t show up in Homekit, while being controllable through the Homebridge UI.

The plugin "g30r93g/homebridge-panasonic" does work fine in that regard.

I've already moved the plugin to its own child bridge, which sadly shows no accessories in Homekit.

**Comment by AntonioMeireles** [comment]
@lDavidl 

Thanks for reporting. 

a) child bridges aren't compatible with this plugin as it is a 'Platform' one. We need it to be that way so that we can support cleanly multiple TV sets. 
b) regarding the TV not appearing in HomeKit, 
   Do you have added the TV manually to Homekit (via home app) ? If you don't see it ...
   you may need to...
  - delete the `accessories/vieramatic.json` (inside your homebridge config dir)...
  - restart homebridge 
  - then add TV to homekit via home.app as each TV is a separate accessory 


All the best, 

António

**Comment by lDavidl** [comment]
Hi, thanks for the super quick reply! 

I can't believe that I didn't even try to add it manually, it totally worked!

I'm also happy to see that this plugin, unlike the one previously mentioned, doesn't just toggle the TV on/off but appears to have proper dedicated command for both on and off..

Due to that, the other plugin always toggled the TV off if it was on when trying to switch inputs with a Scene, since all Scenes have Turn On command, too. So input and app switching through Siri works quite well now :D 

Thanks a lot for this plugin, it'll get a lot of use ffrom me!

**Comment by AntonioMeireles** [comment]
@lDavidl 

glad it's all sorted :-) have fun. 

feel free to bug me again if need arises. 

Will close per your feedback. 

All the best, and a great weekend!

António

P.S. just pushed a new version a few secs ago.

**Comment by lDavidl** [comment]
@AntonioMeireles 

Will do, although it does appear to do all that I wanted from it already! :) 
Great weekend to you too!

David
