### ISSUE TITLE
No Wake on Lan on my TV?

### ISSUE THREAD

**Issue by mariomaz87** [AntonioMeireles/homebridge-vieramatic#96]
Hi,
I have a very old plasma TV (TX-P42UT50E), bought in 2012.
In the Network link settings of the TV I have DLNA Remote Control and Network Remote Control to "on". I can't turn on the TV using Homebridge (but I can turn it off). I have configured the MAC Address and also enable the workaround for old TVs.
```json
{
    "platform": "PanasonicVieraTV",
    "tvs": [
        {
            "customVolumeSlider": false,
            "disabledAppSupport": true,
            "friendlyName": "Televisione",
            "hdmiInputs": [
                {
                    "id": "2",
                    "name": "Streaming"
                }
            ],
            "ipAddress": "192.168.1.80",
            "mac": "8c:c1:21:16:ae:d0"
        }
    ]
}
```

I noticed that when the TV is off, I can't ping it.
Do I have to try with the HDMI input to turn it on or I'm a missing somethings?

Thanks!

**Comment by AntonioMeireles** [comment]
@mariomaz87 

hi! 

you TV may or may not support WOL, if it does it will be only via ethernet and not wireless. 

the best way to know is "simple" ... 

just try WOL manually and see if TV wakes... if it does *then* it should also do via the plugin (or there's a bug that i'll help you debug and fix) otherwise nothing i can do...

so on your homebridge box install `etherwake`, then check which is your default interface then ...
(let's  assume it is `eth0`... run `etherwake -i eth0 8c:c1:21:16:ae:d0` 

if it works and TV wakes up - WOL is supported, otherwise TV just too old.

**Comment by mariomaz87** [comment]
Thanks, I tried sending the WOL package but the TV did not respond. I guess it’s too old then. Thanks again!
